version: "3.2"

services:
  mysqldb:
    image: mysql:5.7
    restart: always
    networks:
      - network1
    volumes:
      - mysql-data:/var/lib/mysql

    environment:
      MYSQL_ROOT_PASSWORD: blabla 
      MYSQL_DATABASE: omeka
      MYSQL_USER: omeka
      MYSQL_PASSWORD: omeka
      explicit_defaults_for_timestamp: 1
      
  pma:
    depends_on:
      - mysqldb
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    networks:
      - network1 
    ports:
      - "8080:80"
    links:
      - mysqldb:db

  omeka:
    depends_on:
      - mysqldb
    image: pbcote/omeka-s_dev2:v1.2
    restart: always
    networks:
      - network1 
    ports:
      - "80:80"
    links:
      - mysqldb:db
    volumes:
      - type: bind
        source: /current_work/projects/cambridge/chc_omeka/cdash_dev/chc_omeka_files
        target: /var/www/html/chc_omeka_files

volumes:
  mysql-data:

networks:
  network1:  
